# Loom Settings
fabric-loom.skipRemapSources=true
org.gradle.java.home=C:/Users/negi6/java/jdk-25.0.4+7

# Minecraft version: 26.1, 26.1.1, 26.1.2, or 26.2
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version=1.0.0
maven_group=com.example
archives_base_name=hitcolour

# Dependencies (18.0.0 for 26.1, 20.0.1 for 26.2)
modmenu_version=18.0.0
yacl_version=3.9.5+26.1-fabric
