# Loom Settings
fabric-loom.skipRemapSources=true
org.gradle.java.home=C:/Users/negi6/java/jdk-21.0.12+8

# Minecraft version: 1.21.11
minecraft_version=1.21.11
loader_version=0.19.3

# Mod Properties
mod_version=1.0.0
maven_group=com.example
archives_base_name=hitcolour

# Dependencies (17.0.0 for 1.21.11)
modmenu_version=17.0.1-beta.1
yacl_version=3.8.1+1.21.11-fabric
